### ISSUE TITLE
Issue with TestImages means the lazy loading isn't actually lazy

### ISSUE THREAD

**Issue by tlnagy** [ElisabethRoesch/Perspective_Julia_for_Biologists#5]
Hi :wave:, it's the author of [`TiffImages.jl`](https://github.com/tlnagy/TiffImages.jl) here. I really like your example for working with lazy images in Julia and I was playing around with the code and I realized that the type of the MRI image is incorrect for lazily-loaded images. 

```julia
julia> testimage("mri"; mmap = true)
3-dimensional AxisArray{ColorTypes.Gray{FixedPointNumbers.N0f8},3,...} with axes:
    :P, 0:1:225
    :R, 0:1:185
    :S, 0:5:130
And data, a 226×186×27 Array{Gray{N0f8},3} with eltype ColorTypes.Gray{FixedPointNumbers.N0f8}:
```
The `AxisArray` type wraps what looks like an eagerly evaluated `Array` type. It appears that this is underlying bug in `TestImages` where it eagerly realizes the lazy image for the MRI stack specifically: https://github.com/JuliaImages/TestImages.jl/blob/0326957a0db943e01dbcbcd45dda13ee331bb910/src/TestImages.jl#L133 and was introduced in commit https://github.com/JuliaImages/TestImages.jl/commit/e3a2d3180e1a09648e520d998c69a0358a733c20.

Removing the forced conversion gives the correct type: `TiffImages.MmappedTIFF` (see docs https://tamasnagy.com/TiffImages.jl/stable/lib/public/#TiffImages.MmappedTIFF)

```julia
julia> testimage("mri"; mmap = true)
3-dimensional AxisArray{ColorTypes.Gray{FixedPointNumbers.N0f8},3,...} with axes:
    :P, 0:1:225
    :R, 0:1:185
    :S, 0:5:130
And data, a 226×186×27 TiffImages.MmappedTIFF{ColorTypes.Gray{FixedPointNumbers.N0f8}, 3} with 27 slice planes:
```

I'm pushing a fix to `TestImages.jl` to remove this forced conversion, but I expect that this might change the timings for Supplementary Figure 1 @ElisabethRoesch @timholy

**Comment by timholy** [comment]
~Are you sure that `convert` isn't a no-op? I added a `@show isa(img, Array{Gray{N0f8},3})` before the `convert` statement and got `true`. And the relevant `convert` method is a no-op: https://github.com/JuliaLang/julia/blob/master/base/array.jl#L666~

~So I'm guessing there's nothing actually wrong with the example, but I agree we should remove the `convert` statement.~

EDIT: ah, with kwarg `mmap=true` it's not correct. So I think you're right. Thanks for catching this.

**Comment by timholy** [comment]
Fortunately, the timing differences are so small they may not be relevant:
```julia
shell> cat timing_julia.txt
Julia
Scalar: 8.782782782782783e-9
Slice: 4.615e-9
Slice copy: 7.6428e-5
n      tview     tcopy
---    -----     -----
  2    5.13e-09  4.04e-08
  4    6.3e-09  5.04e-08
  8    5.13e-09  1.5e-07
 16    5.12e-09  4.14e-07
 32    6.31e-09  1.73e-06
 64    6.3e-09  7.52e-06
128    5.13e-09  2.42e-05

shell> cat timing_julia_0.txt
Julia
Scalar: 6.962962962962963e-9
Slice: 4.62e-9
Slice copy: 6.1105e-5
n      tview     tcopy
---    -----     -----
  2    5.11e-09  4.03e-08
  4    5.11e-09  5.38e-08
  8    5.12e-09  1.21e-07
 16    6.33e-09  4.15e-07
 32    5.14e-09  2.11e-06
 64    5.12e-09  6.09e-06
128    6.32e-09  2.4e-05
```
The first was after removing the `convert`, the second before. I haven't tested whether these are in the noise, but they don't seem likely to be far from that. Not sure we need to update the figure.

**Comment by tlnagy** [comment]
That looks pretty much the same to me. So I guess most of the speed benefits come from the lazy ops and not the lazy loading for such a small image!

**Comment by timholy** [comment]
Yeah, the lazy-loading's real benefit is that it makes it possible to do at all (when the file size is large, unlike this small demo), not that it makes it faster.
